name: tsql_linter

on: push

jobs:
  build:
    name: Check code with TSQL Linter
    runs-on: ubuntu-latest

    steps:
      - run: echo "----------- BEGIN --------"

      - name: Checkout source code
        uses: actions/checkout@v3

      - run: ls

      - id: sql-file-folder
        shell: pwsh
        run: |
          folderName=$($(Get-Date).Year).$($(Get-Date).Month.ToString("00"))
          echo "folder=$folderName" >> $GITHUB_OUTPUT

      - name: SQL Lint
        id: sql-lint
        uses: im-open/tsql-lint-action@v1.1.0
        with:
          tsqllint-version: 1.11.0
          path-to-sql-files: "Database/src/Migrations/${{ steps.sql-file-folder.outputs.folder }}"
          file-name-filter: "*.sql"
          path-to-lint-config: ./.tsqllintrc
      
      - name: Print Lint Result
        run: echo '${{ steps.sql-lint.outputs.lint-result }}'

      - run: echo "----------- END --------"