name: tsql_linter

on: push

jobs:
  build:
    name: Check code with TSQL Linter
    runs-on: ubuntu-latest

    steps:
      - run: echo "----------- BEGIN --------"

      - name: Checkout source code
        uses: actions/checkout@v3

      - run: ls


      - name: Run TSQLLint
        uses: lowlydba/tsqllint-action@v0.8.0
        with:
          path: "*.sql"
          config: "./.tsqllintrc"
          comment: true

      - run: echo "----------- END --------"