name: tsql_linter

on: push

jobs:
  build:
    name: Check code with TSQL Linter
    runs-on: ubuntu-latest

    steps:
      - run: echo "----------- BEGIN --------"

      - name: "NPM Version"
        run: npm version

      - name: "Install TSQLLint"
        run: npm i -g tsqllint 

      - name: "Run Lint"
        run: npm --prefix ${{ github.action_path }} run lint -- "./02-select/demo/" -c ./.tsqllintrc

      # - name: Checkout source code
      #   uses: actions/checkout@v3

      - run: ls -la ./

      # - run: ls ./02-select/demo/

      # - name: SQL Lint
      #   id: sql-lint
      #   uses: im-open/tsql-lint-action@v1.1.0
      #   with:
      #     tsqllint-version: 1.15.1
      #     path-to-sql-files: "02-select/demo/ 02-select/homework/"
      #     file-name-filter: "*.sql"
      #     path-to-lint-config: ".tsqllintrc"
      
      # - name: Print Lint Result
      #   run: echo '${{ steps.sql-lint.outputs.lint-result }}'

      - run: echo "----------- END --------"