name: tsql_linter

on: push

jobs:
  build:
    name: Check code with TSQL Linter
    runs-on: ubuntu-latest

    steps:
      - run: echo "----------- BEGIN --------"

      - name: Checkout source code
        uses: actions/checkout@v3

      - run: echo "----------- END --------"

